---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    create_containers: 1
    container_name: hugo
    container_image: hugo-image
    local_port: 8080

  tasks:
  - name: Create containers
    docker_container:
      name: "{{ container_name }}{{ item }}"
      image: "{{ container_image }}"
      state: started
      published_ports:
        - "{{ local_port }}:80"
    with_sequence: count={{ create_containers }}
